"""init schema

Revision ID: 0d8dcd6e61ad
Revises: 
Create Date: 2026-02-26 13:58:30.738861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8dcd6e61ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_contents_key'), ['key'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('detail_text', sa.Text(), nullable=False),
    sa.Column('detail_images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verify_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_code', sa.Boolean(), nullable=False),
    sa.Column('warning_threshold', sa.Integer(), nullable=False),
    sa.Column('recent_events_limit', sa.Integer(), nullable=False),
    sa.Column('contact_us_url', sa.String(length=1024), nullable=False),
    sa.Column('text_genuine', sa.String(length=255), nullable=False),
    sa.Column('text_not_found', sa.String(length=255), nullable=False),
    sa.Column('text_warning', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('disabled_reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_status'), ['status'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_sort_order'), ['sort_order'], unique=False)

    op.create_table('anti_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('disabled_reason', sa.String(length=255), nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('first_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anti_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anti_codes_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anti_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_anti_codes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anti_codes_status'), ['status'], unique=False)

    op.create_table('scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anti_code_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('visitor_id', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('ua_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['anti_code_id'], ['anti_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_events_anti_code_id'), ['anti_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_events_scanned_at'), ['scanned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_events_visitor_id'), ['visitor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_events_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_scan_events_scanned_at'))
        batch_op.drop_index(batch_op.f('ix_scan_events_anti_code_id'))

    op.drop_table('scan_events')
    with op.batch_alter_table('anti_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anti_codes_status'))
        batch_op.drop_index(batch_op.f('ix_anti_codes_product_id'))
        batch_op.drop_index(batch_op.f('ix_anti_codes_code'))
        batch_op.drop_index(batch_op.f('ix_anti_codes_batch_id'))

    op.drop_table('anti_codes')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_sort_order'))
        batch_op.drop_index(batch_op.f('ix_recommendations_product_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_enabled'))

    op.drop_table('recommendations')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_status'))
        batch_op.drop_index(batch_op.f('ix_batches_product_id'))

    op.drop_table('batches')
    op.drop_table('verify_configs')
    op.drop_table('products')
    with op.batch_alter_table('page_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_contents_key'))

    op.drop_table('page_contents')
    # ### end Alembic commands ###
